### PR TITLE
re-organize files and flow

### PR DESCRIPTION
**Pull request by ajschumacher**
Hi @laumontemayor! There's still more to do, but this file structure is closer to what we want, I think.

Major to-dos:
- drastically simplify the install step
- add python exercises
- make every page except the readme include a section that students will edit in their forks, even if it's just a "hello world" kind of edit

### CODE REVIEW

**Comment by lauraxm** [comment]
hi! @ajschumacher 
- I'll add some Python stuff later today at submit a PR. Should we also include duration of each section, maybe in the main page? 
- Do you think we should separate the stats exercises into separate files so we get alerted every time they commit an exercise?

**Comment by ajschumacher** [comment]
Hi @laumontemayor!
- Cool!
- What if we did "duration" as "number of books you need to read"? I'm not sure estimating "five hours" (for example) is the best thing to do... But maybe? I'm not sure.
- Why would we be alerted more often if there are more files? Oh! Are we thinking that they won't do small commits? It would be a nice way separate out individual questions though, for sure~ :sandal:

**Comment by ajschumacher** [comment]
Oh! I meant to create issues earlier. I'll do that now.

**Comment by lauraxm** [comment]
@ajschumacher 
- I've got a ton of exercises now, so I'm thinking of creating a Python folder and putting the exercises in a separate file. What do you think?  I'm also going to add extra resources to the "main"  Python 
- I like the idea of "number of books you need to read" - I guess I want to outline how much time  students should make for the pre-work. Another thing to think about. 
- Ha! Yes, I didn't think anyone would do small commits as much as a big "here's my answer!" submission. Hmmm. The only reason why keeping them separate would be a good idea is if we're going to provide any kind of feedback on individual exercises ... in my head one day the students will also give feedback to each other... maybe?  :lollipop:

**Comment by ajschumacher** [comment]
Yes! :lollipop:

**Pull request merged**
